package:
    type:           yii2-extension
    name:           hipanel-module-document
    title:          HiPanel Documents package
    headline:       HiPanel Documents Package
    homepage:       https://hipanel.com/
    keywords:       hipanel, control panel, hosting, domains, documents
    namespace:      hipanel
    description: |
        [![Logo](https://raw.githubusercontent.com/hiqdev/hipanel-core/master/docs/logo.png)](https://hipanel.com/)

        [HiPanel](http://hipanel.com) is next generation control panel for hosting, domains and more.

        This package is the core of the system.

